//
//  StreamModel.swift
//  FossTube
//
//  Created by Shrey Soni on 19/09/22.
//

import Foundation

struct StreamModel:Codable {
    let title, welcome10Description, uploadDate, uploader: String?
    let uploaderURL: String?
    let uploaderAvatar: String?
    let thumbnailURL: String?
    let hls: String?
    let dash, lbryID: String?
    let uploaderVerified: Bool?
    let duration, views, likes, dislikes: Int?
    let uploaderSubscriberCount: Int?
    let audioStreams, videoStreams: [AVStream]
    let relatedStreams: [RelatedStream]
    let subtitles: [Subtitle]
    let livestream: Bool?
    let proxyURL: String?
    //    let chapters: [Any?]
}

struct AVStream:Codable {
    let url: String?
    let format, quality, mimeType: String?
    let codec: String?
    let videoOnly: Bool?
    let bitrate, initStart, initEnd, indexStart: Int?
    let indexEnd, width, height, fps: Int?
}

struct RelatedStream: Codable {
    let url, title: String?
    let thumbnail: String?
    let uploaderName, uploaderURL: String?
    let uploaderAvatar: String?
    let uploadedDate: String?
    let shortDescription: String?
    let duration, views, uploaded: Int?
    let uploaderVerified: Bool?
}

struct Subtitle:Codable {
    let url: String?
    let mimeType, name, code: String?
    let autoGenerated: Bool?
}
